### ISSUE TITLE
How to declare a permissions level?

### ISSUE THREAD

**Issue by haydenwalker980** [GlowingRain/DiscordJS-Bot-Template#7]
I've discovered code for it, yet IDK how to declare it.

**Comment by haydenwalker980** [comment]
@GlowingRain

**Comment by GlowingRain** [comment]
@haydenwalker980 If you're talking about assigning a permLevel to a command, just add the **`permLevel`** property and the numeric value before the command execution. ~~You caught me off-guard, I barely even remember the code for this one.~~

**Comment by haydenwalker980** [comment]
Alright thanks.
